% Final
clear;
clc;
close all;

% Save figures
fig = struct( ...
	'wid',		30, ...
	'hei',		20, ...
	'col',		'rgb',...
	'res',		300, ...
	'lax',		true, ...
	'fmo',		'fixed', ...
	'fsi',		12, ...
	'lmo',		'scaled', ...
	'fmt',		'pdf' ...
	);

[f11, S11, Z0] = readSparamFile('../meas/0521/s11.s1p');
[f21, S21, Z0] = readSparamFile('../meas/0521/s21.s1p');
[f12, S12, Z0] = readSparamFile('../meas/0521/s12.s1p');
[f22, S22, Z0] = readSparamFile('../meas/0521/s22.s1p');

max(20*log10(abs(S11)))
max(20*log10(abs(S22)))

h = [0 0 0 0];
figure(1);
clf;

hold on;
h(3) = plot(f12 / 1e9, 20*log10(abs(S12)), 'linewidth', 2, 'color', 'g');
h(1) = plot(f11 / 1e9, 20*log10(abs(S11)), 'linewidth', 2, 'color', 'r');
h(4) = plot(f22 / 1e9, 20*log10(abs(S22)), 'linewidth', 2, 'color', 'b');
h(2) = plot(f21 / 1e9, 20*log10(abs(S21)), 'linewidth', 2, 'color', 'k');
hold off;

grid on;
xlabel('Frequency $$f$$ [GHz]', 'interpreter', 'latex');
ylabel('Magnitude $$|S_{ij}|$$ [dB]', 'interpreter', 'latex');
title('Measured $$S$$-parameters of the amplifier', 'interpreter', 'latex');
legend(h, {'$$S_{11}$$', '$$S_{21}$$', '$$S_{12}$$', '$$S_{22}$$'}, ...
	'location', 'southeast', 'interpreter', 'latex', 'orientation', 'horizontal');

orient landscape;
exportfig(gcf, ['../meas/0521/sparam.', fig.fmt], ...
	'width',		fig.wid, ...
	'height',		fig.hei, ...
	'color',		fig.col, ...
	'resolution',	fig.res, ...
	'LockAxes',		fig.lax, ...
	'FontMode',		fig.fmo, ...
	'FontSize',		fig.fsi, ...
	'LineMode',		fig.lmo, ...
	'Format',		fig.fmt	);

interpFunc = 'pchip'; 	% Interpolation function
