% Final
clear;
clc;
close all;

% Save figures
figs = struct( ...
	'global',	false, ...
	'horn',		true, ...
	'imp',		false, ...
	's11',		true, ...
	'horn2',	true, ...
	'apc',		true, ...
	'refl',		true, ...
	'patch',	true, ...
	'array',	true, ...
	'xpd',		true ...
	);
interpFunc = 'pchip'; 	% Interpolation function
